(define-module (game start-screen)
               #:export (draw))

(use-modules (ncurses curses)
             (util reader)
             (util colors)
             (util debug))

(define welcome-message (color-string "%c4;Lets%c %bstart%b this up"))
(define i 0)

(define (draw scr)
  (let ((as (add-async 300 (λ ()
                              (addchstr scr (color-string "[ %i%c4;~a%c%i ]" i) #:x 0 #:y 0)
                              (addch scr (blink #\X) #:x (1- (getmaxx scr)) #:y (1- (getmaxy scr)))
                              (set! i (1+ i))))))
    (let redraw-loop ((mx (getmaxx scr))
                      (my (getmaxy scr)))
      (catch 'window-resize
        (λ ()
           (erase scr)
           (addchstr scr welcome-message #:x (- (floor/ mx 2) (floor/ (length welcome-message) 2)) #:y (floor/ my 2)) 
           (get-char scr)
           (drop-async as))
        (λ (key . args)
           (redraw-loop (getmaxx scr) (getmaxy scr)))))))
